// Generated by openapi-typescript from the backend's OpenAPI spec — do not hand-edit.
// Regenerate with `pnpm run generate-api-types` after a DTO shape changes.
export interface paths {
    "/api/audiobook/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PathDto"];
                    "text/json": components["schemas"]["PathDto"];
                    "application/*+json": components["schemas"]["PathDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Audiobook"];
                        "application/json": components["schemas"]["Audiobook"];
                        "text/json": components["schemas"]["Audiobook"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/organize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrganizeAudiobookDto"];
                    "text/json": components["schemas"]["OrganizeAudiobookDto"];
                    "application/*+json": components["schemas"]["OrganizeAudiobookDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/generate_path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrganizeAudiobookDto"];
                    "text/json": components["schemas"]["OrganizeAudiobookDto"];
                    "application/*+json": components["schemas"]["OrganizeAudiobookDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/check_target_path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrganizeAudiobookDto"];
                    "text/json": components["schemas"]["OrganizeAudiobookDto"];
                    "application/*+json": components["schemas"]["OrganizeAudiobookDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TargetPathCheckDto"];
                        "application/json": components["schemas"]["TargetPathCheckDto"];
                        "text/json": components["schemas"]["TargetPathCheckDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrganizeAudiobookDto"];
                    "text/json": components["schemas"]["OrganizeAudiobookDto"];
                    "application/*+json": components["schemas"]["OrganizeAudiobookDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobook/{id}/save-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookSaveStatusDto"];
                        "application/json": components["schemas"]["AudiobookSaveStatusDto"];
                        "text/json": components["schemas"]["AudiobookSaveStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/audiobooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookSummaryDtoPaginatedResult"];
                        "application/json": components["schemas"]["AudiobookSummaryDtoPaginatedResult"];
                        "text/json": components["schemas"]["AudiobookSummaryDtoPaginatedResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/library-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LibrarySearchResultDto"];
                        "application/json": components["schemas"]["LibrarySearchResultDto"];
                        "text/json": components["schemas"]["LibrarySearchResultDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/audiobooks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookSummaryDtoPaginatedResult"];
                        "application/json": components["schemas"]["AudiobookSummaryDtoPaginatedResult"];
                        "text/json": components["schemas"]["AudiobookSummaryDtoPaginatedResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthorSummaryDto"][];
                        "application/json": components["schemas"]["AuthorSummaryDto"][];
                        "text/json": components["schemas"]["AuthorSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/authors/{authorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    authorId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthorDetailDto"];
                        "application/json": components["schemas"]["AuthorDetailDto"];
                        "text/json": components["schemas"]["AuthorDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/audiobooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookDetailDto"];
                        "application/json": components["schemas"]["AudiobookDetailDto"];
                        "text/json": components["schemas"]["AudiobookDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/audiobooks/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seriesName?: string;
                    authorId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookSummaryDto"][];
                        "application/json": components["schemas"]["AudiobookSummaryDto"][];
                        "text/json": components["schemas"]["AudiobookSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConsistencyIssueDto"][];
                        "application/json": components["schemas"]["ConsistencyIssueDto"][];
                        "text/json": components["schemas"]["ConsistencyIssueDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": {
                            [key: string]: number;
                        };
                        "application/json": {
                            [key: string]: number;
                        };
                        "text/json": {
                            [key: string]: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues/by-audiobook/{audiobookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    audiobookId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConsistencyIssueDto"][];
                        "application/json": components["schemas"]["ConsistencyIssueDto"][];
                        "text/json": components["schemas"]["ConsistencyIssueDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues/recheck/{audiobookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    audiobookId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues/resolve-by-type/{issueType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    issueType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues/resolve-selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": number[];
                    "text/json": number[];
                    "application/*+json": number[];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/issues/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/orphan-directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrphanDirectoryDto"][];
                        "application/json": components["schemas"]["OrphanDirectoryDto"][];
                        "text/json": components["schemas"]["OrphanDirectoryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/orphan-directories/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consistency/orphan-directories/resolve-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/directory_contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PathDto"];
                    "text/json": components["schemas"]["PathDto"];
                    "application/*+json": components["schemas"]["PathDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookFileInfo"][];
                        "application/json": components["schemas"]["AudiobookFileInfo"][];
                        "text/json": components["schemas"]["AudiobookFileInfo"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    path?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/delete_directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PathDto"];
                    "text/json": components["schemas"]["PathDto"];
                    "application/*+json": components["schemas"]["PathDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/discovered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DiscoveredAudiobookDtoPaginatedResult"];
                        "application/json": components["schemas"]["DiscoveredAudiobookDtoPaginatedResult"];
                        "text/json": components["schemas"]["DiscoveredAudiobookDtoPaginatedResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    path?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/discovered/bulk-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BulkImportDiscoveredDto"];
                    "text/json": components["schemas"]["BulkImportDiscoveredDto"];
                    "application/*+json": components["schemas"]["BulkImportDiscoveredDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata-search/{sourceName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    sourceName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MetadataSearchResult"][];
                        "application/json": components["schemas"]["MetadataSearchResult"][];
                        "text/json": components["schemas"]["MetadataSearchResult"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata-search/multi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MetadataMultiSearchDto"];
                    "text/json": components["schemas"]["MetadataMultiSearchDto"];
                    "application/*+json": components["schemas"]["MetadataMultiSearchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MetadataMultiSourceSearchResult"];
                        "application/json": components["schemas"]["MetadataMultiSourceSearchResult"];
                        "text/json": components["schemas"]["MetadataMultiSourceSearchResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata-search/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PathDto"];
                    "text/json": components["schemas"]["PathDto"];
                    "application/*+json": components["schemas"]["PathDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MetadataSearchResult"];
                        "application/json": components["schemas"]["MetadataSearchResult"];
                        "text/json": components["schemas"]["MetadataSearchResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata-search/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MetadataSearchServiceInfo"][];
                        "application/json": components["schemas"]["MetadataSearchServiceInfo"][];
                        "text/json": components["schemas"]["MetadataSearchServiceInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata-search/proxy-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    url?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missing-tags/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MissingTagFieldDto"][];
                        "application/json": components["schemas"]["MissingTagFieldDto"][];
                        "text/json": components["schemas"]["MissingTagFieldDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missing-tags/audiobooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    fields?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AudiobookMissingTagsDto"][];
                        "application/json": components["schemas"]["AudiobookMissingTagsDto"][];
                        "text/json": components["schemas"]["AudiobookMissingTagsDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missing-tags/backfill-language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{key}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OperationStatusDto"];
                        "application/json": components["schemas"]["OperationStatusDto"];
                        "text/json": components["schemas"]["OperationStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesOverviewDto"][];
                        "application/json": components["schemas"]["SeriesOverviewDto"][];
                        "text/json": components["schemas"]["SeriesOverviewDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesDetailDto"];
                        "application/json": components["schemas"]["SeriesDetailDto"];
                        "text/json": components["schemas"]["SeriesDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/match-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesMatchCandidateDto"][];
                        "application/json": components["schemas"]["SeriesMatchCandidateDto"][];
                        "text/json": components["schemas"]["SeriesMatchCandidateDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/match-candidates/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seriesName?: string;
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesMatchCandidateDto"][];
                        "application/json": components["schemas"]["SeriesMatchCandidateDto"][];
                        "text/json": components["schemas"]["SeriesMatchCandidateDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MatchSeriesDto"];
                    "text/json": components["schemas"]["MatchSeriesDto"];
                    "application/*+json": components["schemas"]["MatchSeriesDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesOverviewDto"];
                        "application/json": components["schemas"]["SeriesOverviewDto"];
                        "text/json": components["schemas"]["SeriesOverviewDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/include-omnibus-editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IncludeOmnibusEditionsDto"];
                    "text/json": components["schemas"]["IncludeOmnibusEditionsDto"];
                    "application/*+json": components["schemas"]["IncludeOmnibusEditionsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesOverviewDto"];
                        "application/json": components["schemas"]["SeriesOverviewDto"];
                        "text/json": components["schemas"]["SeriesOverviewDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/match/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BulkMatchSeriesDto"];
                    "text/json": components["schemas"]["BulkMatchSeriesDto"];
                    "application/*+json": components["schemas"]["BulkMatchSeriesDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/expected-books/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExpectedBookRefDto"];
                    "text/json": components["schemas"]["ExpectedBookRefDto"];
                    "application/*+json": components["schemas"]["ExpectedBookRefDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/expected-books/unignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    seriesName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExpectedBookRefDto"];
                    "text/json": components["schemas"]["ExpectedBookRefDto"];
                    "application/*+json": components["schemas"]["ExpectedBookRefDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LanguageOptionsDto"];
                        "application/json": components["schemas"]["LanguageOptionsDto"];
                        "text/json": components["schemas"]["LanguageOptionsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/series_mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesMapping"][];
                        "application/json": components["schemas"]["SeriesMapping"][];
                        "text/json": components["schemas"]["SeriesMapping"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SeriesMapping"];
                    "text/json": components["schemas"]["SeriesMapping"];
                    "application/*+json": components["schemas"]["SeriesMapping"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesMapping"];
                        "application/json": components["schemas"]["SeriesMapping"];
                        "text/json": components["schemas"]["SeriesMapping"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/series_mappings/{mappingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mappingId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SeriesMapping"];
                    "text/json": components["schemas"]["SeriesMapping"];
                    "application/*+json": components["schemas"]["SeriesMapping"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeriesMapping"];
                        "application/json": components["schemas"]["SeriesMapping"];
                        "text/json": components["schemas"]["SeriesMapping"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mappingId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similar-values/similar-authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimilarValueGroupDto"][];
                        "application/json": components["schemas"]["SimilarValueGroupDto"][];
                        "text/json": components["schemas"]["SimilarValueGroupDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similar-values/similar-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimilarValueGroupDto"][];
                        "application/json": components["schemas"]["SimilarValueGroupDto"][];
                        "text/json": components["schemas"]["SimilarValueGroupDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similar-values/author-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similar-values/series-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similar-values/align": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AlignSimilarValuesDto"];
                    "text/json": components["schemas"]["AlignSimilarValuesDto"];
                    "application/*+json": components["schemas"]["AlignSimilarValuesDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/untagged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetUntaggedAudiobookFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlignSimilarValuesDto: {
            valueType?: string | null;
            sourceValues?: string[] | null;
            targetValue?: string | null;
        };
        Audiobook: {
            /** Format: int64 */
            id?: number | null;
            authors?: components["schemas"]["Person"][] | null;
            narrators?: components["schemas"]["Person"][] | null;
            bookName?: string | null;
            subtitle?: string | null;
            series?: string | null;
            seriesPart?: string | null;
            /** Format: int32 */
            year?: number | null;
            genres?: string[] | null;
            description?: string | null;
            copyright?: string | null;
            publisher?: string | null;
            language?: string | null;
            rating?: string | null;
            asin?: string | null;
            www?: string | null;
            cover?: components["schemas"]["AudiobookImage"];
            coverFilePath?: string | null;
            /** Format: int32 */
            durationInSeconds?: number | null;
            fileInfo?: components["schemas"]["AudiobookFileInfo"];
        };
        AudiobookDetailDto: {
            /** Format: int64 */
            id?: number;
            bookName?: string | null;
            subtitle?: string | null;
            series?: string | null;
            seriesPart?: string | null;
            /** Format: int32 */
            year?: number | null;
            authors?: string[] | null;
            narrators?: string[] | null;
            genres?: string[] | null;
            description?: string | null;
            copyright?: string | null;
            publisher?: string | null;
            language?: string | null;
            rating?: string | null;
            asin?: string | null;
            www?: string | null;
            coverFilePath?: string | null;
            /** Format: int32 */
            durationInSeconds?: number | null;
            filePath?: string | null;
            fileName?: string | null;
            /** Format: int64 */
            sizeInBytes?: number;
        };
        AudiobookFileInfo: {
            fullPath?: string | null;
            fileName?: string | null;
            /** Format: int64 */
            sizeInBytes?: number;
        };
        AudiobookFileInfoPaginatedResult: {
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            total?: number;
            items?: components["schemas"]["AudiobookFileInfo"][] | null;
        };
        AudiobookImage: {
            base64Data?: string | null;
            mimeType?: string | null;
        };
        AudiobookMissingTagsDto: {
            /** Format: int64 */
            audiobookId?: number;
            bookName?: string | null;
            authors?: string[] | null;
            missingFields?: string[] | null;
        };
        AudiobookSaveStatusDto: {
            /** Format: int64 */
            audiobookId?: number;
            isSaving?: boolean;
        };
        AudiobookSummaryDto: {
            /** Format: int64 */
            id?: number;
            bookName?: string | null;
            subtitle?: string | null;
            series?: string | null;
            seriesPart?: string | null;
            /** Format: int32 */
            year?: number | null;
            authors?: string[] | null;
            narrators?: string[] | null;
            genres?: string[] | null;
            coverFilePath?: string | null;
            /** Format: int32 */
            durationInSeconds?: number | null;
        };
        AudiobookSummaryDtoPaginatedResult: {
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            total?: number;
            items?: components["schemas"]["AudiobookSummaryDto"][] | null;
        };
        AuthorDetailDto: {
            author?: components["schemas"]["AuthorSummaryDto"];
            series?: components["schemas"]["SeriesInfo"][] | null;
            standaloneBooks?: components["schemas"]["AudiobookSummaryDto"][] | null;
        };
        AuthorSummaryDto: {
            /** Format: int64 */
            id?: number;
            name?: string | null;
            /** Format: int32 */
            bookCount?: number;
        };
        BulkImportDiscoveredDto: {
            paths?: string[] | null;
        };
        BulkMatchSeriesDto: {
            /** Format: double */
            confidenceThreshold?: number;
            seriesNames?: string[] | null;
        };
        ConsistencyIssueDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            audiobookId?: number;
            bookName?: string | null;
            authors?: string[] | null;
            issueType?: string | null;
            description?: string | null;
            expectedValue?: string | null;
            actualValue?: string | null;
            /** Format: date-time */
            detectedAt?: string;
        };
        DiscoveredAudiobookDto: {
            fullPath?: string | null;
            fileName?: string | null;
            /** Format: int64 */
            sizeInBytes?: number;
            bookName?: string | null;
            subtitle?: string | null;
            series?: string | null;
            seriesPart?: string | null;
            /** Format: int32 */
            year?: number | null;
            authors?: string | null;
            narrators?: string | null;
            genres?: string | null;
            description?: string | null;
            copyright?: string | null;
            publisher?: string | null;
            language?: string | null;
            rating?: string | null;
            asin?: string | null;
            www?: string | null;
            /** Format: int32 */
            durationInSeconds?: number | null;
            isWellTagged?: boolean;
            isDuplicate?: boolean;
        };
        DiscoveredAudiobookDtoPaginatedResult: {
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            total?: number;
            items?: components["schemas"]["DiscoveredAudiobookDto"][] | null;
        };
        ExistingTargetFileDto: {
            /** Format: int64 */
            audiobookId?: number | null;
            /** Format: int64 */
            sizeInBytes?: number;
            /** Format: int32 */
            durationInSeconds?: number | null;
        };
        ExpectedBookRefDto: {
            position?: string | null;
            title?: string | null;
        };
        IncludeOmnibusEditionsDto: {
            includeOmnibusEditions?: boolean;
        };
        LanguageOptionDto: {
            code?: string | null;
            displayName?: string | null;
            aliases?: string[] | null;
        };
        LanguageOptionsDto: {
            languages?: components["schemas"]["LanguageOptionDto"][] | null;
            defaultCode?: string | null;
        };
        LibraryAuthorHitDto: {
            /** Format: int64 */
            id?: number;
            name?: string | null;
            /** Format: int32 */
            bookCount?: number;
        };
        LibraryBookHitDto: {
            /** Format: int64 */
            id?: number;
            bookName?: string | null;
            subtitle?: string | null;
            authors?: string[] | null;
            series?: string | null;
            /** Format: int32 */
            year?: number | null;
            coverFilePath?: string | null;
        };
        LibrarySearchResultDto: {
            books?: components["schemas"]["LibraryBookHitDto"][] | null;
            authors?: components["schemas"]["LibraryAuthorHitDto"][] | null;
            series?: components["schemas"]["LibrarySeriesHitDto"][] | null;
        };
        LibrarySeriesHitDto: {
            name?: string | null;
            /** Format: int32 */
            bookCount?: number;
        };
        MatchSeriesDto: {
            sourceName?: string | null;
            sourceId?: string | null;
            /** Format: double */
            confidence?: number | null;
            includeOmnibusEditions?: boolean;
        };
        MetadataMultiSearchDto: {
            sources?: string[] | null;
            q?: string | null;
        };
        MetadataMultiSourceSearchResult: {
            results?: components["schemas"]["MetadataSearchResult"][] | null;
            sourceStatuses?: components["schemas"]["MetadataSourceSearchStatus"][] | null;
        };
        MetadataSearchResult: {
            url?: string | null;
            source?: string | null;
            authors?: components["schemas"]["Person"][] | null;
            narrators?: components["schemas"]["Person"][] | null;
            bookName?: string | null;
            subtitle?: string | null;
            duration?: string | null;
            /** Format: int32 */
            year?: number | null;
            language?: string | null;
            imageUrl?: string | null;
            series?: components["schemas"]["MetadataSeriesSearchResult"][] | null;
            description?: string | null;
            genres?: string[] | null;
            /** Format: float */
            rating?: number | null;
            /** Format: int32 */
            numberOfRatings?: number | null;
            copyright?: string | null;
            publisher?: string | null;
            asin?: string | null;
            isbn?: string | null;
        };
        MetadataSearchServiceInfo: {
            name?: string | null;
            enabled?: boolean;
            disabledReason?: string | null;
        };
        MetadataSeriesSearchResult: {
            seriesName?: string | null;
            seriesPart?: string | null;
            originalSeriesName?: string | null;
            partWarning?: boolean | null;
        };
        MetadataSourceSearchStatus: {
            source?: string | null;
            success?: boolean;
            /** Format: int32 */
            resultCount?: number;
            error?: string | null;
        };
        MissingTagFieldDto: {
            key?: string | null;
            label?: string | null;
            isCriticalByDefault?: boolean;
        };
        OperationStatusDto: {
            isRunning?: boolean;
            /** Format: int32 */
            processed?: number;
            /** Format: int32 */
            total?: number;
        };
        OrganizeAudiobookCoverDto: {
            base64Data: string;
            mimeType: string;
        };
        OrganizeAudiobookDto: {
            bookName: string;
            subtitle?: string | null;
            series?: string | null;
            seriesPart?: string | null;
            /** Format: int32 */
            year: number;
            authors: string[];
            narrators?: string[] | null;
            genres?: string[] | null;
            description?: string | null;
            copyright?: string | null;
            publisher?: string | null;
            language?: string | null;
            rating?: string | null;
            asin?: string | null;
            www?: string | null;
            cover?: components["schemas"]["OrganizeAudiobookCoverDto"];
            filePath: string;
            fileName: string;
            /** Format: int64 */
            sizeInBytes?: number;
        };
        OrphanDirectoryDto: {
            /** Format: int64 */
            id?: number;
            directoryPath?: string | null;
            /** Format: date-time */
            detectedAt?: string;
        };
        PathDto: {
            path: string | null;
        };
        Person: {
            /** Format: int64 */
            id?: number | null;
            name?: string | null;
            role?: string | null;
        };
        SeriesDetailDto: {
            overview?: components["schemas"]["SeriesOverviewDto"];
            ownedBooks?: components["schemas"]["SeriesOwnedBookDto"][] | null;
            missingBooks?: components["schemas"]["SeriesExpectedBookDto"][] | null;
            ignoredBooks?: components["schemas"]["SeriesExpectedBookDto"][] | null;
        };
        SeriesExpectedBookDto: {
            /** Format: int64 */
            id?: number;
            title?: string | null;
            position?: string | null;
            /** Format: int32 */
            year?: number | null;
            sourceUrl?: string | null;
            isIgnored?: boolean;
        };
        SeriesInfo: {
            seriesName?: string | null;
            /** Format: int32 */
            bookCount?: number;
        };
        SeriesMapping: {
            /** Format: int64 */
            id?: number | null;
            regex?: string | null;
            mappedSeries?: string | null;
            warnAboutPart?: boolean;
        };
        SeriesMatchCandidateDto: {
            sourceName?: string | null;
            sourceId?: string | null;
            seriesName?: string | null;
            sourceUrl?: string | null;
            authors?: string[] | null;
            /** Format: int32 */
            bookCount?: number | null;
            /** Format: double */
            confidence?: number;
        };
        SeriesOverviewDto: {
            /** Format: int64 */
            id?: number | null;
            name?: string | null;
            authors?: string[] | null;
            /** Format: int32 */
            ownedBookCount?: number;
            isMatched?: boolean;
            matchedSourceName?: string | null;
            matchedSourceId?: string | null;
            matchedSourceUrl?: string | null;
            /** Format: double */
            matchConfidence?: number | null;
            /** Format: date-time */
            lastRefreshedAt?: string | null;
            /** Format: int32 */
            expectedBookCount?: number;
            /** Format: int32 */
            missingBookCount?: number;
            /** Format: int32 */
            ignoredBookCount?: number;
            includeOmnibusEditions?: boolean;
        };
        SeriesOwnedBookDto: {
            /** Format: int64 */
            id?: number;
            bookName?: string | null;
            seriesPart?: string | null;
            /** Format: int32 */
            year?: number;
            authors?: string[] | null;
            narrators?: string[] | null;
            /** Format: int32 */
            durationInSeconds?: number | null;
        };
        SimilarValueBookDto: {
            /** Format: int64 */
            id?: number;
            bookName?: string | null;
        };
        SimilarValueCandidateDto: {
            value?: string | null;
            /** Format: int32 */
            bookCount?: number;
            books?: components["schemas"]["SimilarValueBookDto"][] | null;
        };
        SimilarValueGroupDto: {
            candidates?: components["schemas"]["SimilarValueCandidateDto"][] | null;
        };
        TargetPathCheckDto: {
            targetPath?: string | null;
            exists?: boolean;
            existing?: components["schemas"]["ExistingTargetFileDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetUntaggedAudiobookFiles: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["AudiobookFileInfoPaginatedResult"];
                    "application/json": components["schemas"]["AudiobookFileInfoPaginatedResult"];
                    "text/json": components["schemas"]["AudiobookFileInfoPaginatedResult"];
                };
            };
        };
    };
}
