/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsistencyRouteImport } from './routes/consistency'
import { Route as MissingTagsRouteImport } from './routes/missing-tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimilarValuesRouteImport } from './routes/similar-values'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryCleanUrlsRouteImport } from './routes/library/clean-urls'
import { Route as LibraryConsistencyRouteImport } from './routes/library/consistency'
import { Route as LibraryDiscoveredRouteImport } from './routes/library/discovered'
import { Route as LibraryMissingTagsRouteImport } from './routes/library/missing-tags'
import { Route as LibrarySimilarValuesRouteImport } from './routes/library/similar-values'
import { Route as LibraryAuthorsIndexRouteImport } from './routes/library/authors/index'
import { Route as LibraryAuthorsAuthorIdRouteImport } from './routes/library/authors/$authorId'
import { Route as LibraryBookBookIdRouteImport } from './routes/library/book.$bookId'
import { Route as LibrarySeriesIndexRouteImport } from './routes/library/series/index'
import { Route as LibrarySeriesSeriesNameRouteImport } from './routes/library/series/$seriesName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsistencyRoute = ConsistencyRouteImport.update({
  id: '/consistency',
  path: '/consistency',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingTagsRoute = MissingTagsRouteImport.update({
  id: '/missing-tags',
  path: '/missing-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimilarValuesRoute = SimilarValuesRouteImport.update({
  id: '/similar-values',
  path: '/similar-values',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCleanUrlsRoute = LibraryCleanUrlsRouteImport.update({
  id: '/library/clean-urls',
  path: '/library/clean-urls',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryConsistencyRoute = LibraryConsistencyRouteImport.update({
  id: '/library/consistency',
  path: '/library/consistency',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryDiscoveredRoute = LibraryDiscoveredRouteImport.update({
  id: '/library/discovered',
  path: '/library/discovered',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMissingTagsRoute = LibraryMissingTagsRouteImport.update({
  id: '/library/missing-tags',
  path: '/library/missing-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySimilarValuesRoute = LibrarySimilarValuesRouteImport.update({
  id: '/library/similar-values',
  path: '/library/similar-values',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAuthorsIndexRoute = LibraryAuthorsIndexRouteImport.update({
  id: '/library/authors/',
  path: '/library/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAuthorsAuthorIdRoute = LibraryAuthorsAuthorIdRouteImport.update({
  id: '/library/authors/$authorId',
  path: '/library/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBookBookIdRoute = LibraryBookBookIdRouteImport.update({
  id: '/library/book/$bookId',
  path: '/library/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySeriesIndexRoute = LibrarySeriesIndexRouteImport.update({
  id: '/library/series/',
  path: '/library/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySeriesSeriesNameRoute = LibrarySeriesSeriesNameRouteImport.update({
  id: '/library/series/$seriesName',
  path: '/library/series/$seriesName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consistency': typeof ConsistencyRoute
  '/missing-tags': typeof MissingTagsRoute
  '/settings': typeof SettingsRoute
  '/similar-values': typeof SimilarValuesRoute
  '/library/clean-urls': typeof LibraryCleanUrlsRoute
  '/library/consistency': typeof LibraryConsistencyRoute
  '/library/discovered': typeof LibraryDiscoveredRoute
  '/library/missing-tags': typeof LibraryMissingTagsRoute
  '/library/similar-values': typeof LibrarySimilarValuesRoute
  '/library/': typeof LibraryIndexRoute
  '/library/authors/$authorId': typeof LibraryAuthorsAuthorIdRoute
  '/library/book/$bookId': typeof LibraryBookBookIdRoute
  '/library/series/$seriesName': typeof LibrarySeriesSeriesNameRoute
  '/library/authors/': typeof LibraryAuthorsIndexRoute
  '/library/series/': typeof LibrarySeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consistency': typeof ConsistencyRoute
  '/missing-tags': typeof MissingTagsRoute
  '/settings': typeof SettingsRoute
  '/similar-values': typeof SimilarValuesRoute
  '/library/clean-urls': typeof LibraryCleanUrlsRoute
  '/library/consistency': typeof LibraryConsistencyRoute
  '/library/discovered': typeof LibraryDiscoveredRoute
  '/library/missing-tags': typeof LibraryMissingTagsRoute
  '/library/similar-values': typeof LibrarySimilarValuesRoute
  '/library': typeof LibraryIndexRoute
  '/library/authors/$authorId': typeof LibraryAuthorsAuthorIdRoute
  '/library/book/$bookId': typeof LibraryBookBookIdRoute
  '/library/series/$seriesName': typeof LibrarySeriesSeriesNameRoute
  '/library/authors': typeof LibraryAuthorsIndexRoute
  '/library/series': typeof LibrarySeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consistency': typeof ConsistencyRoute
  '/missing-tags': typeof MissingTagsRoute
  '/settings': typeof SettingsRoute
  '/similar-values': typeof SimilarValuesRoute
  '/library/clean-urls': typeof LibraryCleanUrlsRoute
  '/library/consistency': typeof LibraryConsistencyRoute
  '/library/discovered': typeof LibraryDiscoveredRoute
  '/library/missing-tags': typeof LibraryMissingTagsRoute
  '/library/similar-values': typeof LibrarySimilarValuesRoute
  '/library/': typeof LibraryIndexRoute
  '/library/authors/$authorId': typeof LibraryAuthorsAuthorIdRoute
  '/library/book/$bookId': typeof LibraryBookBookIdRoute
  '/library/series/$seriesName': typeof LibrarySeriesSeriesNameRoute
  '/library/authors/': typeof LibraryAuthorsIndexRoute
  '/library/series/': typeof LibrarySeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consistency'
    | '/missing-tags'
    | '/settings'
    | '/similar-values'
    | '/library/clean-urls'
    | '/library/consistency'
    | '/library/discovered'
    | '/library/missing-tags'
    | '/library/similar-values'
    | '/library/'
    | '/library/authors/$authorId'
    | '/library/book/$bookId'
    | '/library/series/$seriesName'
    | '/library/authors/'
    | '/library/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consistency'
    | '/missing-tags'
    | '/settings'
    | '/similar-values'
    | '/library/clean-urls'
    | '/library/consistency'
    | '/library/discovered'
    | '/library/missing-tags'
    | '/library/similar-values'
    | '/library'
    | '/library/authors/$authorId'
    | '/library/book/$bookId'
    | '/library/series/$seriesName'
    | '/library/authors'
    | '/library/series'
  id:
    | '__root__'
    | '/'
    | '/consistency'
    | '/missing-tags'
    | '/settings'
    | '/similar-values'
    | '/library/clean-urls'
    | '/library/consistency'
    | '/library/discovered'
    | '/library/missing-tags'
    | '/library/similar-values'
    | '/library/'
    | '/library/authors/$authorId'
    | '/library/book/$bookId'
    | '/library/series/$seriesName'
    | '/library/authors/'
    | '/library/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsistencyRoute: typeof ConsistencyRoute
  MissingTagsRoute: typeof MissingTagsRoute
  SettingsRoute: typeof SettingsRoute
  SimilarValuesRoute: typeof SimilarValuesRoute
  LibraryCleanUrlsRoute: typeof LibraryCleanUrlsRoute
  LibraryConsistencyRoute: typeof LibraryConsistencyRoute
  LibraryDiscoveredRoute: typeof LibraryDiscoveredRoute
  LibraryMissingTagsRoute: typeof LibraryMissingTagsRoute
  LibrarySimilarValuesRoute: typeof LibrarySimilarValuesRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryAuthorsAuthorIdRoute: typeof LibraryAuthorsAuthorIdRoute
  LibraryBookBookIdRoute: typeof LibraryBookBookIdRoute
  LibrarySeriesSeriesNameRoute: typeof LibrarySeriesSeriesNameRoute
  LibraryAuthorsIndexRoute: typeof LibraryAuthorsIndexRoute
  LibrarySeriesIndexRoute: typeof LibrarySeriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consistency': {
      id: '/consistency'
      path: '/consistency'
      fullPath: '/consistency'
      preLoaderRoute: typeof ConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-tags': {
      id: '/missing-tags'
      path: '/missing-tags'
      fullPath: '/missing-tags'
      preLoaderRoute: typeof MissingTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/similar-values': {
      id: '/similar-values'
      path: '/similar-values'
      fullPath: '/similar-values'
      preLoaderRoute: typeof SimilarValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/clean-urls': {
      id: '/library/clean-urls'
      path: '/library/clean-urls'
      fullPath: '/library/clean-urls'
      preLoaderRoute: typeof LibraryCleanUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/consistency': {
      id: '/library/consistency'
      path: '/library/consistency'
      fullPath: '/library/consistency'
      preLoaderRoute: typeof LibraryConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/discovered': {
      id: '/library/discovered'
      path: '/library/discovered'
      fullPath: '/library/discovered'
      preLoaderRoute: typeof LibraryDiscoveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/missing-tags': {
      id: '/library/missing-tags'
      path: '/library/missing-tags'
      fullPath: '/library/missing-tags'
      preLoaderRoute: typeof LibraryMissingTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/similar-values': {
      id: '/library/similar-values'
      path: '/library/similar-values'
      fullPath: '/library/similar-values'
      preLoaderRoute: typeof LibrarySimilarValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/authors/': {
      id: '/library/authors/'
      path: '/library/authors'
      fullPath: '/library/authors/'
      preLoaderRoute: typeof LibraryAuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/authors/$authorId': {
      id: '/library/authors/$authorId'
      path: '/library/authors/$authorId'
      fullPath: '/library/authors/$authorId'
      preLoaderRoute: typeof LibraryAuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/book/$bookId': {
      id: '/library/book/$bookId'
      path: '/library/book/$bookId'
      fullPath: '/library/book/$bookId'
      preLoaderRoute: typeof LibraryBookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/series/': {
      id: '/library/series/'
      path: '/library/series'
      fullPath: '/library/series/'
      preLoaderRoute: typeof LibrarySeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/series/$seriesName': {
      id: '/library/series/$seriesName'
      path: '/library/series/$seriesName'
      fullPath: '/library/series/$seriesName'
      preLoaderRoute: typeof LibrarySeriesSeriesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsistencyRoute: ConsistencyRoute,
  MissingTagsRoute: MissingTagsRoute,
  SettingsRoute: SettingsRoute,
  SimilarValuesRoute: SimilarValuesRoute,
  LibraryCleanUrlsRoute: LibraryCleanUrlsRoute,
  LibraryConsistencyRoute: LibraryConsistencyRoute,
  LibraryDiscoveredRoute: LibraryDiscoveredRoute,
  LibraryMissingTagsRoute: LibraryMissingTagsRoute,
  LibrarySimilarValuesRoute: LibrarySimilarValuesRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryAuthorsAuthorIdRoute: LibraryAuthorsAuthorIdRoute,
  LibraryBookBookIdRoute: LibraryBookBookIdRoute,
  LibrarySeriesSeriesNameRoute: LibrarySeriesSeriesNameRoute,
  LibraryAuthorsIndexRoute: LibraryAuthorsIndexRoute,
  LibrarySeriesIndexRoute: LibrarySeriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
