// <auto-generated />
using System;
using AudiobookManager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudiobookManager.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260829050318_AddLookupIndexes")]
    partial class AddLookupIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AudiobookGenre", b =>
                {
                    b.Property<long>("BooksId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("books_id");

                    b.Property<long>("GenresId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("genres_id");

                    b.HasKey("BooksId", "GenresId")
                        .HasName("pk_audiobook_genre");

                    b.HasIndex("GenresId")
                        .HasDatabaseName("ix_audiobook_genre_genres_id");

                    b.ToTable("audiobook_genre", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.Audiobook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT")
                        .HasColumnName("asin");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_name");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT")
                        .HasColumnName("copyright");

                    b.Property<string>("CoverFilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_file_path");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("FileInfoFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_info_file_name");

                    b.Property<string>("FileInfoFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_info_full_path");

                    b.Property<long>("FileInfoSizeInBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_info_size_in_bytes");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT")
                        .HasColumnName("series");

                    b.Property<string>("SeriesPart")
                        .HasColumnType("TEXT")
                        .HasColumnName("series_part");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitle");

                    b.Property<string>("Www")
                        .HasColumnType("TEXT")
                        .HasColumnName("www");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_audiobooks");

                    b.HasIndex(new[] { "FileInfoFileName" }, "ix_audiobooks_file_info_file_name")
                        .HasDatabaseName("ix_audiobooks_file_info_file_name");

                    b.HasIndex(new[] { "FileInfoFullPath" }, "ix_audiobooks_file_info_full_path")
                        .HasDatabaseName("ix_audiobooks_file_info_full_path");

                    b.HasIndex(new[] { "Series" }, "ix_audiobooks_series")
                        .HasDatabaseName("ix_audiobooks_series");

                    b.ToTable("audiobooks", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.ConsistencyIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActualValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("actual_value");

                    b.Property<long>("AudiobookId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("audiobook_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<string>("ExpectedValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_value");

                    b.Property<int>("IssueType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issue_type");

                    b.HasKey("Id")
                        .HasName("pk_consistency_issues");

                    b.HasIndex("AudiobookId")
                        .HasDatabaseName("ix_consistency_issues_audiobook_id");

                    b.ToTable("consistency_issues", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.DiscoveredAudiobook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT")
                        .HasColumnName("asin");

                    b.Property<string>("Authors")
                        .HasColumnType("TEXT")
                        .HasColumnName("authors");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_name");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT")
                        .HasColumnName("copyright");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("discovered_at");

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("FileInfoFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_info_file_name");

                    b.Property<string>("FileInfoFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_info_full_path");

                    b.Property<long>("FileInfoSizeInBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_info_size_in_bytes");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT")
                        .HasColumnName("genres");

                    b.Property<string>("Narrators")
                        .HasColumnType("TEXT")
                        .HasColumnName("narrators");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT")
                        .HasColumnName("series");

                    b.Property<string>("SeriesPart")
                        .HasColumnType("TEXT")
                        .HasColumnName("series_part");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitle");

                    b.Property<string>("Www")
                        .HasColumnType("TEXT")
                        .HasColumnName("www");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_discovered_audiobooks");

                    b.HasIndex(new[] { "FileInfoFullPath" }, "ix_discovered_audiobooks_file_info_full_path")
                        .HasDatabaseName("ix_discovered_audiobooks_file_info_full_path");

                    b.ToTable("discovered_audiobooks", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.HardcoverRequestQuota", b =>
                {
                    b.Property<DateOnly>("UtcDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("utc_date");

                    b.Property<int>("RequestCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("request_count");

                    b.HasKey("UtcDate")
                        .HasName("pk_hardcover_request_quota");

                    b.ToTable("hardcover_request_quota", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.OrphanDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("directory_path");

                    b.HasKey("Id")
                        .HasName("pk_orphan_directories");

                    b.ToTable("orphan_directories", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.QueuedOrganizeTask", b =>
                {
                    b.Property<string>("OriginalFileLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_location");

                    b.Property<string>("JsonAudiobook")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json_audiobook");

                    b.Property<DateTime>("QueuedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("queued_time");

                    b.HasKey("OriginalFileLocation")
                        .HasName("pk_queued_organize_task");

                    b.ToTable("queued_organize_task", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IncludeOmnibusEditions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_omnibus_editions");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_refreshed_at");

                    b.Property<double?>("MatchConfidence")
                        .HasColumnType("REAL")
                        .HasColumnName("match_confidence");

                    b.Property<string>("MatchedSeriesName")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched_series_name");

                    b.Property<string>("MatchedSourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched_source_id");

                    b.Property<string>("MatchedSourceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched_source_name");

                    b.Property<string>("MatchedSourceUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched_source_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex(new[] { "Name" }, "ix_series_name")
                        .IsUnique()
                        .HasDatabaseName("ix_series_name");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.SeriesExpectedBook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsCompilation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_compilation");

                    b.Property<bool>("IsIgnored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_ignored");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<long>("SeriesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_series_expected_books");

                    b.HasIndex(new[] { "SeriesId" }, "ix_series_expected_books_series_id")
                        .HasDatabaseName("ix_series_expected_books_series_id");

                    b.ToTable("series_expected_books", (string)null);
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.SeriesMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("MappedSeries")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mapped_series");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regex");

                    b.Property<bool>("WarnAboutPart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warn_about_part");

                    b.HasKey("Id")
                        .HasName("pk_series_mapping");

                    b.HasIndex(new[] { "Regex" }, "ix_series_mapping_regex")
                        .IsUnique()
                        .HasDatabaseName("ix_series_mapping_regex");

                    b.ToTable("series_mapping", (string)null);
                });

            modelBuilder.Entity("audiobooks_authors_persons", b =>
                {
                    b.Property<long>("AuthorsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("authors_id");

                    b.Property<long>("BooksAuthoredId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("books_authored_id");

                    b.HasKey("AuthorsId", "BooksAuthoredId")
                        .HasName("pk_audiobooks_authors_persons");

                    b.HasIndex("BooksAuthoredId")
                        .HasDatabaseName("ix_audiobooks_authors_persons_books_authored_id");

                    b.ToTable("audiobooks_authors_persons", (string)null);
                });

            modelBuilder.Entity("audiobooks_narrators_persons", b =>
                {
                    b.Property<long>("BooksNarratedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("books_narrated_id");

                    b.Property<long>("NarratorsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrators_id");

                    b.HasKey("BooksNarratedId", "NarratorsId")
                        .HasName("pk_audiobooks_narrators_persons");

                    b.HasIndex("NarratorsId")
                        .HasDatabaseName("ix_audiobooks_narrators_persons_narrators_id");

                    b.ToTable("audiobooks_narrators_persons", (string)null);
                });

            modelBuilder.Entity("AudiobookGenre", b =>
                {
                    b.HasOne("AudiobookManager.Database.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audiobook_genre_audiobooks_books_id");

                    b.HasOne("AudiobookManager.Database.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audiobook_genre_genres_genres_id");
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.ConsistencyIssue", b =>
                {
                    b.HasOne("AudiobookManager.Database.Models.Audiobook", "Audiobook")
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consistency_issues_audiobooks_audiobook_id");

                    b.Navigation("Audiobook");
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.SeriesExpectedBook", b =>
                {
                    b.HasOne("AudiobookManager.Database.Models.Series", "Series")
                        .WithMany("ExpectedBooks")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_expected_books_series_series_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("audiobooks_authors_persons", b =>
                {
                    b.HasOne("AudiobookManager.Database.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audiobooks_authors_persons_persons_authors_id");

                    b.HasOne("AudiobookManager.Database.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("BooksAuthoredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audiobooks_authors_persons_audiobooks_books_authored_id");
                });

            modelBuilder.Entity("audiobooks_narrators_persons", b =>
                {
                    b.HasOne("AudiobookManager.Database.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("BooksNarratedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audiobooks_narrators_persons_audiobooks_books_narrated_id");

                    b.HasOne("AudiobookManager.Database.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("NarratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audiobooks_narrators_persons_persons_narrators_id");
                });

            modelBuilder.Entity("AudiobookManager.Database.Models.Series", b =>
                {
                    b.Navigation("ExpectedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
