name: CI Formatting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        working-directory: ./client
        run: pnpm install --frozen-lockfile

      - name: Prettier Formatting
        working-directory: ./client
        run: pnpm run format-check
