name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  test-dotnet:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: "10.x"

      - name: Run tests
        working-directory: ./AudiobookManager
        run: dotnet test

  test-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install
        working-directory: ./client
        run: npm ci

      - name: Run tests
        working-directory: ./client
        run: npm test
